# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_hostel.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Qedit_hostel(object):
    def setupUi(self, Qedit_hostel):
        Qedit_hostel.setObjectName("Qedit_hostel")
        Qedit_hostel.resize(760, 248)
        self.country = QtWidgets.QLineEdit(Qedit_hostel)
        self.country.setGeometry(QtCore.QRect(100, 120, 131, 20))
        self.country.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.country.setObjectName("country")
        self.city = QtWidgets.QLineEdit(Qedit_hostel)
        self.city.setGeometry(QtCore.QRect(100, 150, 131, 20))
        self.city.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.city.setObjectName("city")
        self.name_cinema_wr_4 = QtWidgets.QLabel(Qedit_hostel)
        self.name_cinema_wr_4.setGeometry(QtCore.QRect(30, 150, 51, 21))
        self.name_cinema_wr_4.setObjectName("name_cinema_wr_4")
        self.nlevel = QtWidgets.QLineEdit(Qedit_hostel)
        self.nlevel.setGeometry(QtCore.QRect(100, 40, 131, 20))
        self.nlevel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nlevel.setObjectName("nlevel")
        self.sreet = QtWidgets.QLineEdit(Qedit_hostel)
        self.sreet.setGeometry(QtCore.QRect(100, 180, 131, 20))
        self.sreet.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sreet.setObjectName("sreet")
        self.name_cinema_wr_5 = QtWidgets.QLabel(Qedit_hostel)
        self.name_cinema_wr_5.setGeometry(QtCore.QRect(30, 180, 51, 21))
        self.name_cinema_wr_5.setObjectName("name_cinema_wr_5")
        self.nroom = QtWidgets.QLineEdit(Qedit_hostel)
        self.nroom.setGeometry(QtCore.QRect(100, 70, 131, 20))
        self.nroom.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nroom.setObjectName("nroom")
        self.name_cinema_wr_2 = QtWidgets.QLabel(Qedit_hostel)
        self.name_cinema_wr_2.setGeometry(QtCore.QRect(10, 70, 81, 21))
        self.name_cinema_wr_2.setObjectName("name_cinema_wr_2")
        self.house = QtWidgets.QLineEdit(Qedit_hostel)
        self.house.setGeometry(QtCore.QRect(100, 210, 131, 20))
        self.house.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.house.setObjectName("house")
        self.name_cinema_wr_6 = QtWidgets.QLabel(Qedit_hostel)
        self.name_cinema_wr_6.setGeometry(QtCore.QRect(30, 210, 51, 21))
        self.name_cinema_wr_6.setObjectName("name_cinema_wr_6")
        self.name_cinema_wr = QtWidgets.QLabel(Qedit_hostel)
        self.name_cinema_wr.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.name_cinema_wr.setObjectName("name_cinema_wr")
        self.name_cinema_wr_3 = QtWidgets.QLabel(Qedit_hostel)
        self.name_cinema_wr_3.setGeometry(QtCore.QRect(30, 120, 51, 21))
        self.name_cinema_wr_3.setObjectName("name_cinema_wr_3")
        self.textBrowser = QtWidgets.QTextBrowser(Qedit_hostel)
        self.textBrowser.setGeometry(QtCore.QRect(0, 10, 751, 31))
        self.textBrowser.setStyleSheet("background-color: transparent;")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.name_cinema_wr_7 = QtWidgets.QLabel(Qedit_hostel)
        self.name_cinema_wr_7.setGeometry(QtCore.QRect(270, 40, 201, 21))
        self.name_cinema_wr_7.setObjectName("name_cinema_wr_7")
        self.house_2 = QtWidgets.QLineEdit(Qedit_hostel)
        self.house_2.setGeometry(QtCore.QRect(390, 160, 131, 20))
        self.house_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.house_2.setObjectName("house_2")
        self.house_3 = QtWidgets.QLineEdit(Qedit_hostel)
        self.house_3.setGeometry(QtCore.QRect(390, 190, 131, 20))
        self.house_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.house_3.setObjectName("house_3")
        self.name_cinema_wr_8 = QtWidgets.QLabel(Qedit_hostel)
        self.name_cinema_wr_8.setGeometry(QtCore.QRect(270, 160, 51, 21))
        self.name_cinema_wr_8.setObjectName("name_cinema_wr_8")
        self.name_cinema_wr_9 = QtWidgets.QLabel(Qedit_hostel)
        self.name_cinema_wr_9.setGeometry(QtCore.QRect(270, 190, 51, 21))
        self.name_cinema_wr_9.setObjectName("name_cinema_wr_9")
        self.name_cinema_wr_11 = QtWidgets.QLabel(Qedit_hostel)
        self.name_cinema_wr_11.setGeometry(QtCore.QRect(270, 100, 81, 21))
        self.name_cinema_wr_11.setObjectName("name_cinema_wr_11")
        self.name_cinema_wr_12 = QtWidgets.QLabel(Qedit_hostel)
        self.name_cinema_wr_12.setGeometry(QtCore.QRect(270, 130, 81, 21))
        self.name_cinema_wr_12.setObjectName("name_cinema_wr_12")
        self.name_cinema_wr_13 = QtWidgets.QLabel(Qedit_hostel)
        self.name_cinema_wr_13.setGeometry(QtCore.QRect(270, 70, 81, 21))
        self.name_cinema_wr_13.setObjectName("name_cinema_wr_13")
        self.name = QtWidgets.QLineEdit(Qedit_hostel)
        self.name.setGeometry(QtCore.QRect(390, 100, 131, 20))
        self.name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name.setObjectName("name")
        self.fathername = QtWidgets.QLineEdit(Qedit_hostel)
        self.fathername.setGeometry(QtCore.QRect(390, 130, 131, 20))
        self.fathername.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fathername.setObjectName("fathername")
        self.familyname = QtWidgets.QLineEdit(Qedit_hostel)
        self.familyname.setGeometry(QtCore.QRect(390, 70, 131, 20))
        self.familyname.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.familyname.setObjectName("familyname")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Qedit_hostel)
        self.textBrowser_2.setGeometry(QtCore.QRect(550, 40, 201, 31))
        self.textBrowser_2.setStyleSheet("background-color: transparent;")
        self.textBrowser_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.hotel_session = QtWidgets.QLabel(Qedit_hostel)
        self.hotel_session.setGeometry(QtCore.QRect(560, 70, 191, 131))
        self.hotel_session.setMaximumSize(QtCore.QSize(271, 131))
        self.hotel_session.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.hotel_session.setMouseTracking(True)
        self.hotel_session.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.hotel_session.setFrameShape(QtWidgets.QFrame.Box)
        self.hotel_session.setText("")
        self.hotel_session.setObjectName("hotel_session")
        self.btnadd_hostel = QtWidgets.QPushButton(Qedit_hostel)
        self.btnadd_hostel.setGeometry(QtCore.QRect(690, 210, 61, 23))
        self.btnadd_hostel.setStyleSheet("")
        self.btnadd_hostel.setObjectName("btnadd_hostel")

        self.retranslateUi(Qedit_hostel)
        QtCore.QMetaObject.connectSlotsByName(Qedit_hostel)

    def retranslateUi(self, Qedit_hostel):
        _translate = QtCore.QCoreApplication.translate
        Qedit_hostel.setWindowTitle(_translate("Qedit_hostel", "Form"))
        self.name_cinema_wr_4.setText(_translate("Qedit_hostel", "Город"))
        self.name_cinema_wr_5.setText(_translate("Qedit_hostel", "Улица"))
        self.name_cinema_wr_2.setText(_translate("Qedit_hostel", "Кол-во комнат"))
        self.name_cinema_wr_6.setText(_translate("Qedit_hostel", "Дом"))
        self.name_cinema_wr.setText(_translate("Qedit_hostel", "Кол-во этажей"))
        self.name_cinema_wr_3.setText(_translate("Qedit_hostel", "Страна"))
        self.textBrowser.setHtml(_translate("Qedit_hostel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Редактирование гостиницы</span></p></body></html>"))
        self.name_cinema_wr_7.setText(_translate("Qedit_hostel", "Добавление Администратора"))
        self.name_cinema_wr_8.setText(_translate("Qedit_hostel", "login"))
        self.name_cinema_wr_9.setText(_translate("Qedit_hostel", "password"))
        self.name_cinema_wr_11.setText(_translate("Qedit_hostel", "Имя"))
        self.name_cinema_wr_12.setText(_translate("Qedit_hostel", "Отчество"))
        self.name_cinema_wr_13.setText(_translate("Qedit_hostel", "Фамилия"))
        self.textBrowser_2.setHtml(_translate("Qedit_hostel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Список администраторов</span></p></body></html>"))
        self.btnadd_hostel.setText(_translate("Qedit_hostel", "Готово"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Qedit_hostel = QtWidgets.QWidget()
    ui = Ui_Qedit_hostel()
    ui.setupUi(Qedit_hostel)
    Qedit_hostel.show()
    sys.exit(app.exec_())

